title: Opeyemi Christiana Adeyoyin # your name (or website title) here
logo: "/assets/Photo_Circle.png"
description: 
  I enjoy combining my science background with my flair for data in leveraging data-driven insights to drive strategic decision-making and optimize business processes. Skilled Data Analyst with experience across various sectors such as finance, health etc. 
  Proficient in analyzing complex datasets, developing actionable recommendations, and communicating findings effectively to stakeholders.


show_downloads: true
theme: jekyll-theme-minimal
